### ISSUE TITLE
Create a UI layout

### ISSUE THREAD

**Issue by AbhilashKotha** [oss-slu/shelter_volunteers#23] opened 2023-10-09 21:46 UTC
**Describe the solution you'd like**
Create a UI layout that applies to all the pages of the application. It should have a nav bar, a logo, and user info.

**Comment by kate-holdener** [comment] 2023-10-10 03:43
I think this is a duplicate of issue #18

**Comment by kate-holdener** [comment] 2023-10-22 19:29
Duplicate of issue #18

**Closed by kate-holdener** 2023-10-22 19:29 UTC
